name: Upload to Maven Central

on:
  workflow_dispatch:

env:
  CI: "true"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Debug directory
        run: |
          ls -R .

      - name: Create local.properties
        run: |
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> local.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> local.properties
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> local.properties
          echo "signing.password=${{ secrets.SIGNING_KEY_PASSWORD }}" >> local.properties
          echo "signing.keyBase64=${{ secrets.SIGNING_KEY_ASC }}" >> local.properties
          echo "trackIds=${{ secrets.TRACK_IDS }}" >> local.properties
          echo "trackDomain=${{ secrets.TRACK_DOMAIN }}" >> local.properties

      - name: Make gradle executable
        run: chmod +x gradlew

      - name: Publish to Maven Central
        run: |
          ./gradlew \
          :android-sdk:clean \
          :android-sdk:testReleaseUnitTest \
          :android-sdk:assembleRelease \
          :android-sdk:publishMavenPublicationToMavenLocal \
          :android-sdk:uploadToCentralPortal \
          -x test \
          -x check \
          --stacktrace --no-daemon

